### ISSUE TITLE
`lean` leaks

### ISSUE THREAD

**Issue by RalfJung** [maciejhirsz/beef#12]
As [discovered by Miri](https://github.com/maciejhirsz/beef/pull/11#discussion_r394348721), the `lean` variant of beef leaks memory. I verified that by adding this patch
```diff
diff --git a/src/generic.rs b/src/generic.rs
index add1a9b..9fa0981 100644
--- a/src/generic.rs
+++ b/src/generic.rs
@@ -170,6 +170,7 @@ where
     #[inline]
     fn drop(&mut self) {
         if let Some(capacity) = self.capacity() {
+            panic!("dropping!");
             unsafe { T::owned_from_parts::<U>(self.inner, capacity) };
         }
     }
```
and then running `cargo test lean`. Clearly that should drop the contents and thus panic at some point, but it does not.

**Comment by maciejhirsz** [comment]
Oh dear me, when I was reimplementing this into generics I've made two separate mistakes that both separately cause this: https://github.com/maciejhirsz/beef/pull/13/commits/2e75601438a446369bdf04ad4f6dd7d55e208536#diff-b722bb40412152063337bda6ba389775

line 23: MASK_HI was always 0.
line 50: capacity was zeroed before bitshifted.
