### ISSUE TITLE
github ci

### ISSUE THREAD

**Issue by Licenser** [maciejhirsz/beef#22]
What are the thoughts of migrating from Travis to GitHub CI? It allows nice integrations like pull request blocking so silly people like me can't contribute memory leaks unnoticed :/ I'm happy to make a PR for that.

**Comment by maciejhirsz** [comment]
All the tests were passing, so I'm not sure if another CI would catch that. Haven't used GitHub CI, if you say it's better I'm happy to give it a shot.

**Comment by Licenser** [comment]
👍 I'll throw something together, in the end, it's always a taste thing and you got to be comfortable with maintaining it. I'll make a PR and you can take a look.

**Comment by maciejhirsz** [comment]
Solved by #23.
