### ISSUE TITLE
Implement Default for Cow

### ISSUE THREAD

**Issue by grego** [maciejhirsz/beef#31]
std `Cow` implements the `Default` trait, which basically wraps the default version of the borrowed variant. It would be nice to have it also implemented for `beef::Cow`, to allow using it in the contexts where this trait is required.

**Comment by maciejhirsz** [comment]
Published as 0.4.4.

**Comment by pickfire** [comment]
@maciejhirsz I believe you forgot to git tag 0.4.4.

**Comment by maciejhirsz** [comment]
@pickfire cheers, fixed now.
