### ISSUE TITLE
const_str should use 'static lifetime

### ISSUE THREAD

**Issue by zeroflaw** [maciejhirsz/beef#42]
Should the following function signature not use a &'static lifetime? You can't allocate in const so all str must be static. This might even improve performance.

 `pub const fn const_str(val: &'a str) -> Self`

 I have some code at the moment where I can't swap from std::borrow::Cow, because the inferring lifetime parameter can't see that const_str provides a Cow<&'static>.

**Comment by CAD97** [comment]
> You can't allocate in const so all str must be static.

In the future, you'll be able to use const `str::from_utf8_unchecked` to [create non-static const str](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=9e0e2b5af3d3d6d3be6664eb3ad6df5e).

`const_str` is `impl<'a> Cow::<'a, str, Strategy>::const_str(&'a str) -> Cow<'a, str, Strategy>`, so an input `&'static str` should produce an output `Cow<'static, str, _>`. An example of what's failing to typeck would help; it might just be that more type hints are needed.

**Comment by zeroflaw** [comment]
Ah right, didn't know you could do that. I'll put together a minimal example of my failing code.
